name: Execução Diário do Robô

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar robô
        run: python main.py

      - name: Commit do relatório
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add dados/relatorio.csv
          git commit -m "Atualização diária" || echo "Sem alterações"
          git push
